services:
  - type: web
    name: rosseti-bot
    env: go
    buildCommand: go build -o rosseti-bot .
    startCommand: ./rosseti-bot
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: PARSER_API_KEY
        sync: false
